branches:
  only: master
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y latexmk
script:
  - latexmk -pdf chatbots
  - git clone --depth=1 --branch=public git@github.com:jorinvo/chatbots.git public-branch
  - cd public-branch
  # Commit new files
  - mv ../chatbots.pdf .
  - git add --all
  # For debugging
  - git status
  # Push changes
  - git config user.email "bot@qvl.io"
  - git config user.name "CI Bot"
  - 'git commit -am "$(date)"'
  - git push origin public